# Read the Docs configuration file for git-cache
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, set of tools, and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      # Install system dependencies required for documentation building
      - sudo apt-get update
      - sudo apt-get install -y doxygen graphviz
    pre_build:
      # Create necessary directories
      - mkdir -p docs/doxygen

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt