# Read the Docs configuration file for git-cache
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, set of tools, and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
    - build-essential
  jobs:
    pre_build:
      # Create necessary directories and show available source files
      - mkdir -p docs/doxygen
      - echo "Available source files:"
      - ls -la *.c *.h 2>/dev/null || echo "No source files found in root - API docs will be auto-detected"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt