name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libcurl4-openssl-dev libjson-c-dev
        
    - name: Build
      run: |
        make clean
        make cache
        make url-test
        make github
        
    - name: Run URL parsing tests
      run: |
        echo "::group::URL Parsing Tests"
        make url-test-run
        echo "::endgroup::"
        
    - name: Run GitHub API tests
      run: |
        echo "::group::GitHub API Tests"
        make github-test
        echo "::endgroup::"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run integration tests
      run: |
        echo "::group::Integration Tests"
        make cache-test
        echo "::endgroup::"
        
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          *.log
          core
          core.*
          
  lint:
    name: Lint and Code Style
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check file permissions
      run: |
        # Ensure scripts are executable
        test -x tests/run_cache_tests.sh
        test -x tests/run_github_tests.sh
        test -x tests/run_url_tests.sh
        test -x tests/run_all_tests.sh
        
    - name: Check for tabs (Git coding style)
      run: |
        # Git project uses tabs for indentation
        echo "Checking for proper tab usage in all C files..."
        for file in *.c *.h; do
          if [ -f "$file" ]; then
            if grep -q "^    " "$file"; then
              echo "Error: $file contains spaces instead of tabs for indentation"
              exit 1
            fi
          fi
        done
        echo "✓ All C files use tabs for indentation"